# Minimize YUM
yum --assumeyes erase \
  acl \
  apr \
  attr \
  audit \
  authconfig \
  autoconf \
  b43-openfwwf \
  bison \
  bridge-utils \
  byacc \
  bzip2 \
  bzr \
  cloog-ppl \
  cpp \
  cronie \
  cryptsetup-luks \
  cvs \
  cyrus-sasl \
  device-mapper \
  device-mapper-persistent-data \
  dhclient \
  dhcp-common \
  diffstat \
  e2fsprogs \
  e2fsprogs-libs \
  elfutils \
  elfutils-libs \
  epel-release \
  flex \
  fuse \
  gdb \
  git \
  glibc-devel \
  glibc-headers \
  gnutls \
  grub \
  indent \
  iscsi-initiator-utils \
  kbd \
  kbd-misc \
  kernel-headers \
  keyutils \
  libaio \
  libcap-ng \
  libdrm \
  libevent \
  libgfortran \
  libgomp \
  libgssglue \
  libpciaccess \
  libproxy \
  libss \
  libstdc++-devel \
  libudev \
  logrotate \
  m4 \
  mdadm \
  mercurial \
  mpfr \
  mysql-libs \
  newt \
  pakchois \
  passwd \
  patch \
  patchutils \
  pciutils-libs \
  perl \
  plymouth-core-libs \
  plymouth-scripts \
  ppl \
  rcs \
  redhat-logos \
  rsync \
  slang \
  swig \
  system-config-firewall-base \
  tar \
  unzip \
  xfsprogs \
  xz \
  yum-plugin-versionlock \
  yum-utils.noarch \
  2>&1>/dev/null
yum clean all
# Zero data
dd if=/dev/zero of=/tmp/cleanup bs=1024
rm --force /tmp/cleanup